export * from "./state.inteface"
export * from "./movie.interface"
export * from "./genre.interface"
export * from "./response.interface"
export * from "./theme.inteface"
export * from "./profile.interface"
